swagger: "2.0"
info:
  title: "Authentication Microservice"
  description: A authentication microservice for generating tokens.
  contact:
    name: Murat Mayadag
    url: https://github.com/mmayadag
  license:
    name: MIT
    url: https://github.com/mmayadag/s3-auth/blob/master/LICENSE
  version: 1.0.0
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  token:
    type: basic
paths:
  /:
    get:
      description: Returns \"hello, world\" message.
      responses:
        200:
          description: A \"hello, world\" message.
          schema:
            $ref: '#/definitions/Message'
  /secure:
    get:
      security:
        - token: []
      description: Returns a secure message.
      responses:
        200:
          description: A \"hello, world\" message.
          schema:
            $ref: '#/definitions/Message'
        401:
          description: Not authenticated.
definitions:
  Message:
    required:
      - message
    properties:
      message:
        type: string
    example: 
      message: Hello world!